# Generated by Django 5.1.7 on 2025-04-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='desc',
            field=models.CharField(default='I was too lazy to write a description', max_length=255),
        ),
    ]
