# Generated by Django 5.1.7 on 2025-04-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamApp', '0002_game_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='desc',
            field=models.CharField(default='I was too lazy to write a description.', max_length=255),
        ),
    ]
