# Generated by Django 5.1.7 on 2025-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamApp', '0003_alter_game_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
