# Generated by Django 5.1.7 on 2025-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamApp', '0004_alter_game_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='revenue',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
