# Generated by Django 5.1.7 on 2025-04-13 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamApp', '0005_game_revenue_game_visited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created_at'], name='SteamApp_ga_created_74c434_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-visited'], name='SteamApp_ga_visited_c76c5b_idx'),
        ),
    ]
